[tool.black]
line-length = 100
target-version = ['py311']
include = '\.pyi?$'
exclude = '''
^/(
  (
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[tool.pytest.ini_options]
minversion = "6.2.2"
addopts = "-ra -v --cov"

[tool.coverage.run]
omit = [
  ".venv/*",
  "tests/*",
  "setup.py",
  "*__init__.py*",
]
branch = true

[tool.coverage.report]
precision = 2

[tool.ruff]
line-length = 100
target-version = "py311"
