name: CI Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python latest
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync
      - name: Test with pytest
        run: uv run pytest
